// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"

	"go.dagger.io/dagger/sdk/go/dagger"
)

func (r *query) golang(ctx context.Context) (*Golang, error) {

	return new(Golang), nil

}

type golang struct{}
type query struct{}

func main() {
	dagger.Serve(context.Background(), map[string]func(context.Context, dagger.ArgsInput) (interface{}, error){
		"Golang.do": func(ctx context.Context, fc dagger.ArgsInput) (interface{}, error) {
			var bytes []byte
			_ = bytes
			var err error
			_ = err

			var project dagger.FSID

			bytes, err = json.Marshal(fc.Args["project"])
			if err != nil {
				return nil, err
			}
			if err := json.Unmarshal(bytes, &project); err != nil {
				return nil, err
			}

			var opts GoArgs

			bytes, err = json.Marshal(fc.Args["opts"])
			if err != nil {
				return nil, err
			}
			if err := json.Unmarshal(bytes, &opts); err != nil {
				return nil, err
			}

			return (&golang{}).do(ctx,

				project,

				opts,
			)
		},
		"Query.golang": func(ctx context.Context, fc dagger.ArgsInput) (interface{}, error) {
			var bytes []byte
			_ = bytes
			var err error
			_ = err

			return (&query{}).golang(ctx)
		},
	})
}
